# Transforms a pose to a target frame at a target time.
#
# May 7, 2025

# REQUEST
# Source pose
geometry_msgs/PoseStamped source_pose

# Target header
std_msgs/Header target

# Timeout
builtin_interfaces/Duration timeout
---
# RESPONSE
# Result
dua_common_interfaces/CommandResultStamped result

# Target pose
geometry_msgs/PoseStamped target_pose
