# Updates the earth frame with new gps coordinates
#
# March 12, 2025

# REQUEST
std_msgs/Header header      # Frame id and timestamp of the GPS coordinates
float64 lat                 # New GPS latitude for earth frame
float64 lon                 # New GPS longitude for earth frame
float64 alt                 # New GPS altitude for earth frame
---
# RESPONSE
bool success                # Indicate operation result
